language: java
jdk:
- oraclejdk8
script: mvn install
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  skip_cleanup: true

  on:
    tags: true
    all_branches: true
    repo: hakdogan/MongoAtlas

